### ISSUE TITLE
WebApi calls FHIR Service with User Credentials

### ISSUE THREAD

**Issue by Xavina** [microsoft/azure-health-data-services-toolkit#108]
**Tell us what business problem you are trying to solve**
We are developing a WebApi that consumes a FHIR service, running the application using 'DefaultAzureCredential()' with a user logged in through Azure CLI works fine.

```
builder.Services.AddBinding<RestBinding, RestBindingOptions>(options =>
{
  options.BaseAddress = new Uri(configuration.GetValue<string>("FhirServerUrl"));
  options.Credential = new DefaultAzureCredential();
});
```

Next step is protecting the WebApi controllers using [Authorize] attribute, we receive the bearer token in the API that grants the access to it and the operations the user can perform. The scenario is like that:

``` User -> Api  -> FHIR Server ```

How do we manage the credentials to call FHIR server in the name of the user?

I guess the API should request for a new token in the name of the user, and somehow use it in the WebPipeline.

**Describe what behavior a customization to Azure Health Data Services would solve this problem***
Would be nice to have a sample of this situation, I think it is pretty common.

**Does this issue belong as a feature to Azure Health Data Services instead?**
No

**Additional context**
None

Thanks!

**Comment by mikaelweave** [comment]
Hi @Xavina - we are discussing this internally and will get back to you soon.

**Comment by mikaelweave** [comment]
Hi @Xavina,

We currently don’t support the [OnBehalfOfCredential](https://learn.microsoft.com/dotnet/api/azure.identity.onbehalfofcredential?view=azure-dotnet) in an easy, built-in way using the toolkit. @evachen96 has added this into our backlog as we'd need to update our token cache to work with this scenario. Ideally, we would cache the token for each on-behalf-of user, so we don't need to generate a new token for every request.
 
Since we don’t support the `OnBehalfOfCredential` in our “token cache” a workaround is to manually pass the token using an `InputFilter`.
 
**Program.cs**
```csharp
builder.Services.AddBinding<RestBinding, RestBindingOptions>(options =>
{
  options.BaseAddress = new Uri(configuration.GetValue<string>("FhirServerUrl"));
  options. PassThroughAuthorizationHeader = true;
});
```
 
**CustomAuthInputBinding.cs**
 ```csharp
var credential = new OnBehalfOfCredential(<TenantId>, <clientId>, <clientSecret>,  context.Request.Headers.Authorization.Parameter);
var scopes = string[]{ $"{<fhirAddress>.TrimEnd('/')}/.default" }
var accessToken = await _tokenCredential.GetTokenAsync(TokenRequestContext(scopes), <cancellationToken>));
context.Headers.Add(new HeaderNameValuePair("Authorization", accessToken.Token, CustomHeaderType.RequestStatic));
```

**Comment by Xavina** [comment]
Hi @mikaelweave,

Okay, understood, will do it like you are showing in the code snippets.

Many thanks for caring and getting back to me!
