### ISSUE TITLE
Poor Performance using Authenticator and RestBinding

### ISSUE THREAD

**Issue by mikaelweave** [microsoft/azure-health-data-services-toolkit#92]
The built in RestBinding asks for a new access token for every request. This is not performant and is a **blocker to any** production scale workload with this toolkit.

Moreover, the RestBinding creates a new HttpClient for every request which has some performance concerns.

For better performance of the client, I would recommend:
- Using a singleton HttpClient vs creating one for every request. (see [here](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net)).
  - The Azure Sdk also uses singleton clients for their services. Check out the [Azure Client Factory](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/core/Azure.Core/src/Extensions/IAzureClientFactoryBuilderWithCredential.cs) and [this](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/extensions/Microsoft.Extensions.Azure/src/AzureClientFactoryBuilder.cs)

For better performance for token use, I could recommend code to cache an access token and fetch a new one on failure. Azure KeyVault SDK does a good job at this.
- [client](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyClient.cs#L67)
- [token handling](https://github.com/Azure/azure-sdk-for-net/blob/06d818e52746f02e1fce14ab99bb8da4ecc80765/sdk/keyvault/Azure.Security.KeyVault.Shared/src/ChallengeBasedAuthenticationPolicy.cs)

**Comment by skunklab** [comment]
You cannot do token caching *if* it is OnBehalfOf b/c is requires the user assertion of the caller.  Otherwise, you could cache the token in the Authenticator and check for expiry, i.e., whether to get a refresh or new token.

The IHttpClientFactory will work (and yes to config), but should just add another ctor to take IHttpClientFactory as a parameter to the RestRequest, which DI could inject IHttpClientFactory and the "SendAsync" could determine whether IHttpClientFactory exists and use it, if not create a new HttpClient.  If you want to get the full skinny on this, then talk to Henrik.

**Comment by skunklab** [comment]
correct
